---
- name: Create user group
  ansible.builtin.group:
    name: "{{ user_group }}"
    gid: "{{ user_gid }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    group: "{{ user_group }}"
    uid: "{{ user_uid }}"
    home: "{{ user_home }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Add user to sudo group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: sudo,wheel
    append: yes
  when: user_sudo | default(false)

- name: Set up SSH directory for user
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ user_group }}"
    mode: '0700'

- name: Display user creation result
  ansible.builtin.debug:
    msg: "User {{ username }} created successfully with UID {{ user_uid }}"