---
# main.yml - Main Playbook

- name: User and Java Management
  hosts: all
  become: yes
    
  vars:
    # Java Variables
    java_version: "11"  # 8, 11, 17, 21
    java_home: "/opt/java"
    java_urls:
      "8": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u392-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u392b08.tar.gz"
      "11": "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21+9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.21_9.tar.gz"
      "17": "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9+9/OpenJDK17U-jdk_x64_linux_hotspot_17.0.9_9.tar.gz"
      "21": "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1+12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz"
    
  tasks:
      
    # Java Installation Tasks
    - name: Install Java
      ansible.builtin.include_tasks: java_install.yml