---
# main.yml - Main Playbook
- name: User and Java Management
  hosts: all
  become: yes
    
  vars:
    # Java Variables
    java_version: "17"  # 8, 11, 17, 21
    java_home: "/opt/java"
    java_urls:
      "8": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u392-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u392b08.tar.gz"
      "11": "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21+9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.21_9.tar.gz"
      "17": "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9+9/OpenJDK17U-jdk_x64_linux_hotspot_17.0.9_9.tar.gz"
      "21": "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1+12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz"
    

    username: "appuser"
    user_group: "appgroup"
    user_password: "mypassword123"  
    user_sudo: true  


# LVM Variables

    filesystem_dirs:
      - path: "/opt/REDHAT"
        owner: "root"
        group: "root"
        mode: "0755"
        create_disk: true
        size_mb: 100  # 1GB
      - path: "/data/tomcat_logs"
        owner: "{{ username }}"
        group: "{{ user_group }}"
        mode: "0755"
        create_disk: true
        size_mb: 100  # 2GB
      - path: "/data/tomcat_archive"
        owner: "{{ username }}"
        group: "{{ user_group }}"
        mode: "0755"
        create_disk: true
        size_mb: 100  # 5GB
      - path: "/jdump"
        owner: "{{ username }}"
        group: "{{ user_group }}"
        mode: "0755"
        create_disk: true
        size_mb: 100   # 512MB
      - path: "/scripts"
        owner: "{{ username }}"
        group: "{{ user_group }}"
        mode: "0755"
        size_mb: 100
        create_disk: true  # ไม่สร้าง disk image, ใช้ directory ธรรมดา
      - path: "/mdw_app_deploy"
        owner: "{{ username }}"
        group: "{{ user_group }}"
        mode: "0755"
        create_disk: true
        size_mb: 100  # 3GB

    handlers:
      - name: restart nfs
        systemd:
          name: "{{ 'nfs-kernel-server' if ansible_facts['os_family'] == 'Debian' else 'nfs-server' }}"
          state: restarted

  tasks:
      
    # Java Installation Tasks
    # - name: Install Java
    #   ansible.builtin.include_tasks: java_install.yml

    - name: Create User
      include_tasks: user_create.yml

    - name: Setup File Share
      include_tasks: filesystem.yml

    # - name: Setup LVM File Share
    #   include_tasks: lvm_create.yml

