---
# main.yml - Main Playbook
- name: User and Java Management
  hosts: all
  become: yes
    
  vars_files:
    - vars/main.yml 
    - vars/main2.yml 

  tasks:
    # - name: Install Java
    #   ansible.builtin.include_tasks: tasks/java_install.yml  

    # - name: Create User
    #   ansible.builtin.include_tasks: tasks/user_create.yml

    - name: Setup LVM File Share
      ansible.builtin.include_tasks: tasks/filesystem.yml
