---
# Set lvm_device from survey input (only when disk is needed)
- name: Set lvm_device from survey input
  ansible.builtin.set_fact:
    lvm_device: "{{ manual_lvm_device if (manual_lvm_device is defined and manual_lvm_device != '') else '/dev/' + selected_disk_name if (selected_disk_name is defined and selected_disk_name != '') else lvm_device }}"

- name: Validate disk is specified when required
  ansible.builtin.fail:
    msg: |
      ❌ Disk must be specified for '{{ vg_strategy }}' strategy!
      Please specify either 'selected_disk_name' or 'manual_lvm_device'.
  when: 
    - lvm_device is not defined or lvm_device == ""

- name: Get available disks information for validation
  ansible.builtin.command: lsblk -n -o NAME,SIZE,TYPE,MOUNTPOINT,FSTYPE
  register: available_disks_info  
  changed_when: false

- name: Display available disks for reference
  ansible.builtin.debug:
    msg: |
      Available block devices:
      {{ available_disks_info.stdout }}
      
      Selected LVM device: {{ lvm_device }}

- name: Validate selected disk exists
  ansible.builtin.stat:
    path: "{{ lvm_device }}"
  register: disk_stat

- name: Show available disks when selected disk not found
  ansible.builtin.command: lsblk -l
  register: lsblk_list
  changed_when: false
  when: not disk_stat.stat.exists

- name: Display available disks and fail
  ansible.builtin.fail:
    msg: |
      ❌ Selected disk {{ lvm_device }} does not exist!
      
      📋 Available disks:
      {{ lsblk_list.stdout }}
      
      Please select from the available disks above.
  when: not disk_stat.stat.exists

- name: Check if disk is already in use
  ansible.builtin.shell: |
    if pvdisplay {{ lvm_device }} 2>/dev/null; then
      echo "pv_exists"
    elif lsblk -n {{ lvm_device }} | grep -q part; then  
      echo "has_partitions"
    elif lsblk -n {{ lvm_device }} | awk '{print $7}' | grep -q '/'; then
      echo "mounted"
    else
      echo "available"
    fi
  register: disk_status
  changed_when: false
  failed_when: false

- name: Display disk status
  ansible.builtin.debug:
    msg: "Disk {{ lvm_device }} status: {{ disk_status.stdout }}"

- name: Check for disk conflicts in create_new strategy
  ansible.builtin.fail:
    msg: |
      ❌ Disk {{ lvm_device }} is already in use as Physical Volume!
      Status: {{ disk_status.stdout }}
      
      For 'create_new' strategy, please use an unused disk or change to 'extend_existing' strategy.
  when:
    - vg_strategy == 'create_new'
    - disk_status.stdout == 'pv_exists'
    - force_disk_usage is not defined or force_disk_usage != 'true'

- name: Warning if disk already has PV (extend_existing strategy)
  ansible.builtin.debug:
    msg: "INFO: {{ lvm_device }} already has a Physical Volume. Will add to Volume Group."
  when: 
    - vg_strategy == 'extend_existing'
    - disk_status.stdout == 'pv_exists'