---
- name: Parse filesystem configuration from survey
  ansible.builtin.set_fact:
    parsed_filesystems: "{{ filesystem_config | from_yaml }}"
  when: filesystem_config is defined and filesystem_config != ""

- name: Initialize filesystem_dirs
  ansible.builtin.set_fact:
    filesystem_dirs: []

- name: Build filesystem configuration with defaults
  ansible.builtin.set_fact:
    filesystem_dirs: "{{ filesystem_dirs + [enhanced_fs_config] }}"
  vars:
    enhanced_fs_config:
      path: "{{ fs.path }}"
      lv_name: "{{ fs.lv_name }}"
      owner: "{{ fs.owner | default(default_owner) }}"
      group: "{{ fs.group | default(default_group) }}"
      mode: "{{ fs.mode | default(default_mode) }}"
      create_lvm: "{{ fs.create_lvm | default(true) }}"
      size_mb: "{{ fs.size_mb }}"
      fstype: "{{ fs.fstype | default(default_fstype) }}"
      mount_opts: "{{ fs.mount_opts | default(default_mount_opts) }}"
  loop: "{{ parsed_filesystems | default([]) }}"
  loop_control:
    loop_var: fs

- name: Determine LVM device path
  ansible.builtin.set_fact:
    lvm_device: >-
      {{ 
        manual_lvm_device if (manual_lvm_device is defined and manual_lvm_device != '') 
        else ('/dev/' + selected_disk_name) if (selected_disk_name is defined and selected_disk_name != '') 
        else lvm_device 
      }}

- name: Determine VG management approach
  ansible.builtin.set_fact:
    vg_action: >-
      {{ 
        'use_existing' if (use_existing_vg | default(false) | bool) 
        else ('extend' if (vg_action == 'extend') 
        else 'create')
      }}
    volume_group_name: >-
      {{ 
        existing_vg_name if (use_existing_vg | default(false) | bool and existing_vg_name != '') 
        else volume_group_name 
      }}

- name: Validate required variables
  ansible.builtin.assert:
    that:
      - volume_group_name != ""
      - filesystem_dirs | length > 0
      - (lvm_device != "" or vg_action == "use_existing")
    fail_msg: |
      Missing required configuration:
      - volume_group_name: {{ volume_group_name }}
      - lvm_device: {{ lvm_device }} (not required for existing VG)
      - vg_action: {{ vg_action }}
      - filesystem_dirs count: {{ filesystem_dirs | length }}

- name: Install required packages
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: present