- name: Create user group
  ansible.builtin.group:
    name: "{{ user_group }}"
    gid: "{{ user_gid }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    uid: "{{ user_uid }}"
    group: "{{ user_group }}"
    home: "{{ user_home }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Set user password
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ user_password | password_hash('sha512') }}"
  when: user_password is defined

- name: Add user to wheel group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wheel
    append: yes
  when: user_sudo | default(false)