---
- name: Check if Java exists
  ansible.builtin.command: java -version
  register: java_check
  ignore_errors: true
  changed_when: false

- name: Install Java via Package Manager
  when: 
    - java_check.rc != 0
    - use_package_manager | default(true)
  block:
    - name: Install Java package (Ubuntu)
      ansible.builtin.package:
        name: "{{ package_versions.ubuntu[java_version] }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Java package (CentOS/RHEL)
      ansible.builtin.package:
        name: "{{ package_versions.centos[java_version] }}"
        state: present
      when: ansible_os_family == "RedHat"

- name: Install Java via Manual Download
  when: 
    - java_check.rc != 0
    - not (use_package_manager | default(true))
  block:
    - name: Download OpenJDK
      ansible.builtin.get_url:
        url: "{{ java_urls[java_version] }}"
        dest: "/tmp/java.tar.gz"
        mode: '0644'
        
    - name: Create Java folder
      ansible.builtin.file:
        path: "{{ java_home }}"
        state: directory
        mode: '0755'
            
    - name: Extract Java
      ansible.builtin.unarchive:
        src: "/tmp/java.tar.gz"
        dest: "{{ java_home }}"
        remote_src: yes
        extra_opts: ['--strip-components=1']
            
    - name: Set Java PATH for all users
      ansible.builtin.blockinfile:
        path: /etc/profile
        block: |
          # Java Environment Settings
          export JAVA_HOME={{ java_home }}
          export PATH=$JAVA_HOME/bin:$PATH
        mode: '0644'

- name: Verify Java Installation
  ansible.builtin.command: java -version
  register: java_verify
  changed_when: false

- name: Display Java Version
  ansible.builtin.debug:
    msg: "Java installed successfully: {{ java_verify.stderr_lines[0] }}"